name: Android CI

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print env variable
      env:
        FIRST_NAME: hasret
        LAST_NAME: sariyer
      run: |
        echo $FIRST_NAME $LAST_NAME.
    - name: custom script
      run: whoami
    - name: Build with Gradle
      run: ./gradlew app:assembleminapi23admindebug
